language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - "python setup.py install"
    - "pip install coverage"
    - "pip install coveralls"

script:
    - "coverage run --source=pypika setup.py test"

after_success:
    coveralls